default: &default
  adapter: mysql2
  encoding: utf8mb4
  database: cobalt
  username: app
  password: kore
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock
  host: 127.0.0.1
  port: 3308
  timeout: 5000

development:
  <<: *default
